import React, {useState}from 'react';
import Calendars from './Calendars';

const FormsExp = () => {
    const [newname,setName] = useState('');
    let name = "";
    const TakeText = (event) => {
        // event is an object generated by onChange method and target.value holds the value of the input feild
        name = event.target.value;
        // to show the value in real time
        //setName(name);
    }

    const ShowText = (e) => { // e is an object
        e.preventDefault(); // to restrict the default behaviour of reloading after submitting form
        setName(name);
    }
    return(
        <>
        <form onSubmit={ShowText}>
           <div className="formsexp">   
           <Calendars />  
                    <h1 className="heading_form">Hi {newname}!</h1>
                    <input type = "text" placeholder = "Enter your name" onChange={TakeText}/><br/>
                    <button type="submit">Click Here 💂 </button>
            </div>
        </form>
           
        </>
    );
}

export default FormsExp;